[package]
name = "dsa-cli"
version = "0.1.0"
authors = ["benaryorg <binary@benary.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
clap = "^2.33"
roxmltree = "^0.9.0"
error-chain = "^0.12.1"
regex = "^1.3"
rustyline = "^6.0"

