name: ci

on:
# currently unmaintained
#  schedule:
#    - cron: "0 8 * * *"
  push: {}

# Currently not supported, use later I guess
#var:
#  - &build-steps
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: build
#        run: cargo build --verbose
#      - name: test
#        run: cargo test --verbose
#      - name: clippy
#        run: cargo clippy --verbose -- --deny warnings

jobs:
  build-ubuntu:
    #<<: *build-steps
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
      - name: clippy
        run: cargo clippy --verbose -- --deny warnings
  build-windows:
    #<<: *build-steps
    runs-on:
      - windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
      - name: clippy
        run: cargo clippy --verbose -- --deny warnings

